from datetime import datetime
import time
import crc16

'''Class for telemetry data and converting it to a telemetry sentence with checksum'''
class TelemetryPacket:

	'''Constructor (Note: timestamp will be generated by the constructor)'''
	def __init__(self, callsign, sentence_id, lat, lon, alt, in_temp, out_temp, humidity, air_pressure):
		self.callsign 		= callsign
		self.sentence_id	= sentence_id
		self.time 			= datetime.now()
		self.timestamp		= self.time.strftime("%H:%M:%S")
		self.latitude 		= lat
		self.longitude 		= lon
		self.altitude 		= alt
		self.internal_temp 	= in_temp
		self.external_temp 	= out_temp
		self.humidity 		= humidity
		self.air_pressure 	= air_pressure
		self.checksum 		= "0x00"


	'''Calculate the checksum for the telemetry string'''
	def calculate_checksum(self, telemetry_string):
		return hex(crc16.crc16xmodem(telemetry_string, 0xffff))

	'''Generate telemetry sentence'''
	def to_sentence(self):
		sentence = ("$$%s,%d,%s,%.5f,%.5f,%d,%.1f,%.1f,%d,%d" % (self.callsign, self.sentence_id, self.timestamp, self.latitude, self.longitude, self.altitude, self.internal_temp, self.external_temp, self.humidity, self.air_pressure))
		self.checksum = self.calculate_checksum(sentence)
		return ("%s*%s\n" % (sentence, self.checksum))

